theme: jekyll-theme-minimal
title: KubeOMatic
description: KubeOMatic TimeBomb Project
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
github:
  another_url: https://github.com/kubeomatic/k8s-timebomb
#https://github.com/pages-themes/midnight